config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup', to: 'users#new'
  
  resources :articles
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_secure_password
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            length: {minimum:3, maximum: 30}, 
            uniqueness: { case_sensitive: false }

  validates :email, presence: true, 
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, 
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] =  "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      puts "IDDDDDDDDDDDDDDDDD "+ @article.id.to_s
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article Deleted Successfully"
    redirect_to articles_path
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article"
        redirect_to root_path
      end
      
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def signup
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
      
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
    
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "User Updated Successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end
  
  private
    def set_user
      @user = User.find(params[:id])  
    end
    
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  
    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit and update your own profile"
        redirect_to users_path
      end
    end
    
    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article), class: "title" %> 
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small> Created by: <% if article.user %>
                                  <%= article.user.username %>
                                <% else %> 
                                  <%= 'John Doe' %>
                                <% end %>,
                    about <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit article", edit_article_path(article), class: "btn btn-primary" %>
            <%= link_to "Delete article",article_path(article), method: :delete, data: {confirm: "Are you Sure?"}, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
     
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<div class="row forms">
  <div class="col-xs-12 col-md-12">
    <%= form_for @article do |f| %>
    <div class="row">
      <div class="form-group col-md-offset-2 col-md-8">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control", placeholder: "Title for new Article", autofocus: true %>
      </div>
      <div class="col-md-6">
      </div>
    </div>
    <div class="row">
      <div class= "form-group col-md-offset-2 col-md-8">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", placeholder: "Description of article",rows: "10" %>
      </div>
    </div>
      
      <div class="form-group">
        <div class="col-sm-offset-5 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    
    <% end %>
    <div class="col-md-offset-2">
    <p>
    <h4><%= link_to "List articles", articles_path %></h4>
    </p>
    </div>
  
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit existing article </h1>

<%= render 'form' %>

<p>
<h3><%= link_to "View", article_path(@article) %></h3>
</p>

app/views/articles/index.html.erb
<h1 align="center"> List of Articles </h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
        <div class = "row" align="center">
          <div class="col-md-offset-4 col-md-4">
            <li> Created By: </li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %> </li>
            <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %> </li>
            <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %> </small></li>
          </div>
        </div>
      </ul>
  <% end %>
  <h4 align="center" class="description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>

    <div class="article-actions">
      <%= link_to "List articles", articles_path, class: "btn btn-success" %>
      <% if logged_in? && (current_user = @article.user || current_user.admin?) %>
        <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-primary" %>
        <%= link_to "Delete article",article_path(@article), method: :delete, data: {confirm: "Are you Sure?"}, class: "btn btn-danger" %>
      <% end %>
    </div>
</div>
 

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Your Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "SignUp", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <!--<%= debug(params) if Rails.env.development? %>--> 
  <%= yield %>
  

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
    </head>
    <body>
        <div>
            <h1 align="center">Welcome to Rails Blog</h3>
        </div>
        <div>
           <!-- <img src="/assets/Ruby-on-Rails-Slider.jpg" width="100%" alt="Ruby_on_rails_banner"> -->
            <%= image_tag("Ruby-on-Rails-Slider.jpg", :alt => "Ruby_on_rails_banner", :width => "100%") %>
        </div>
        <div class="row partition">
            <div class="col-xs-12 col-md-12 col-lg-12">
            <header align="center">
                <h3 align="center">This is a Ruby on Rails Blog. You can discuss here various concepts and topics of ruby as a programming language and rails as the web framework for developing web application. You can also pickup ideas of different projects that you can make in rails and also can find some brilliant people sharing their code and logic. 
                    <h3>You can SignUp below and join the biggest community of Ruby On Rails here.</h3></h3>
            </header>
            </div>
        <hr />
        <div class="row partition">
            <div class="col-xs-12 col-md-12 col-lg-12">
                <div class="col-md-6 col-xs-6 col-lg-6">
                
                    <h2 align="center"> You can SignUp here below </h2> 
                    <h3 align="center"><%= link_to 'SignUp', signup_path, class: "linkdecor" %></h3>
                <!--<h3><a href="/pages/signup">SignUp path</a></h3> -->
                </div>
            
                <div class="col-md-6 col-xs-6 col-lg-6">
                    <h2 align="center"> If already joined then LogIn here </h2>
                    <h3 align="center"><%= link_to 'LogIn', signup_path, class: "linkdecor" %></h3>
                </div>
            </div>
        </div>
        </div>
        <div>
            <footer align="center">
                <h3>Posted by: Arpit Agarwal</h3>
                <h3>Contact information: <a href="mailto:agarwalarpit22@gmail.com">agarwalarpit22@gmail.com</a>.</h3>
            </footer>
        </div>
    </body>
</html>

app/views/pages/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SignUp</title>
  </head>
  <body>
    <h3>SignUp Page</h3>
    
    <h3 align="center"><%= link_to 'Home', root_path %></h3>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class= "row">
    <div class="col-xs-offset-2 col-xs-8">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prevented this article from getting saved
          </h2>
          <div class="panel-body">
            <% obj.errors.full_messages.each do |msg| %>
              <ul>
                <li> <%= msg %> </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>


<div class="container">
<div class="row">
  <div class="col-md-offset-4 col-xs-12 col-md-4">
    <%= form_for @user do |f| %>
    <div class="panel panel-primary">
      <% if @user.new_record? %>
        <div class="panel-heading" align="center">SignUp</div>
      <% else %>
        <div class="panel-heading" align="center">Update</div>
      <% end %>
      <div class="panel-body">
        <div class="row">
          <div class="form-group col-md-12 col-xs-12">
              <%= f.label :username %>
              <%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true, width: "50px" %>
          </div>
          <div class="col-md-6">
          </div>
        </div>
        <div class="row">
          <div class= "form-group col-md-12 col-xs-12">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
          </div>
        </div>
        <div class="row">
          <div class= "form-group col-md-12 col-xs-12">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
      
        <div class="form-group">
          <div class="col-sm-12" align="center">
            <%= f.submit(@user.new_record? ? "SignUp" : "Update account", class: "btn btn-primary") %>
          </div>
        </div>
      </div>
    </div>
    
    <% end %>
    <div align="center">
    <p>
    <h5><%= link_to "[ Click here to go back to list of articles ]", articles_path %></h5>
    </p>
    </div>
  
  
</div>
</div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers </h1>

<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class = "row">
        <div class="well col-md-offset-4 col-md-4">
          <li><%= link_to gravatar_for(user), user_path(user) %> </li>
          <li class="article-title"><%= link_to user.username, user_path(user) %> </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %> </small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete This User", user_path(user), method: :delete, 
            data: { confirm: "Are you sure you want to delete user and all its articles?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>


<div class="container">
<div class="row">
  <div class="col-md-offset-4 col-xs-12 col-md-4">
    <%= form_for @user do |f| %>
    <div class="panel panel-primary">
      <div class="panel-heading" align="center">SignUp</div>
      <div class="panel-body">
        <div class="row">
          <div class="form-group col-md-12 col-xs-12">
              <%= f.label :username %>
              <%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true, width: "50px" %>
          </div>
          <div class="col-md-6">
          </div>
        </div>
        <div class="row">
          <div class= "form-group col-md-12 col-xs-12">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
          </div>
        </div>
        <div class="row">
          <div class= "form-group col-md-12 col-xs-12">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
      
        <div class="form-group">
          <div class="col-sm-12" align="center">
            <%= f.submit "SignUp", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    
    <% end %>
    <div align="center">
    <p>
    <h5><%= link_to "[ Click here to go back to list of articles ]", articles_path %></h5>
    </p>
    </div>
  
  
</div>
</div>
</div>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %> 's page </h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4" align="center">
    <%= gravatar_for @user %>
  </div>
</div>

<h4 align="center"> <%= @user.username %> 's articles </h4>
<div align="center">
  <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div align="center">
  <%= will_paginate @user_articles %>
</div>